export const LOGIN = "LOGIN";

export const REGISTER = "REGISTER";
export const LOGOUT = "LOGOUT";
export const ADD__PRODUCT = "ADD__PRODUCT";
export const DELETE__PRODUCT = "DELETE__PRODUCT";
export const CHECKOUT = "CHECKOUT";
export const GETITEMSFROMSTORAGE = "GETITEMSFROMSTORAGE";

export const INCREASEITEM = "INCREASEITEM";
export const DECREASEITEM = "DECREASEITEM";
export const GET__CATEGORIES = "GET__CATEGORIES";


export const ADD_WISHLIST = "ADD_WISHLIST";
export const DELETE_WISHLIST = "DELETE_WISHLIST";
export const GET_WISHLIST = "GET_WISHLIST";