import Head from "next/head";
 import dynamic from "next/dynamic";
 import Layout from "../components/layout/layout"
 const Carousel = dynamic(() => import("../components/main/carousel"), {
  ssr: false,
});
const FeaturedProducts = dynamic(() => import("../components/main/featuredProducts"), {
  ssr: false,
});
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" />
      </Head>
       <div className="site">





        
        <div className="site__body">
          <Carousel />
          <div className="block block-features block-features--layout--classic">
            <div className="container">
              <div className="block-features__list">
                <div className="block-features__item">
                  <div className="block-features__icon">
                    <svg width="48px" height="48px">
                      <use xlinkHref="images/sprite.svg#fi-free-delivery-48"></use>
                    </svg>
                  </div>
                  <div className="block-features__content">
                    <div className="block-features__title">Free Shipping</div>
                    <div className="block-features__subtitle"> For orders from $50 </div>
                  </div>
                </div>
                <div className="block-features__divider"></div>
                <div className="block-features__item">
                  <div className="block-features__icon">
                    <svg width="48px" height="48px">
                      <use xlinkHref="images/sprite.svg#fi-24-hours-48"></use>
                    </svg>
                  </div>
                  <div className="block-features__content">
                    <div className="block-features__title">Support 24/7</div>
                    <div className="block-features__subtitle"> Call us anytime </div>
                  </div>
                </div>
                <div className="block-features__divider"></div>
                <div className="block-features__item">
                  <div className="block-features__icon">
                    <svg width="48px" height="48px">
                      <use xlinkHref="images/sprite.svg#fi-payment-security-48"></use>
                    </svg>
                  </div>
                  <div className="block-features__content">
                    <div className="block-features__title">100% Safety</div>
                    <div className="block-features__subtitle"> Only secure payments </div>
                  </div>
                </div>
                <div className="block-features__divider"></div>
                <div className="block-features__item">
                  <div className="block-features__icon">
                    <svg width="48px" height="48px">
                      <use xlinkHref="images/sprite.svg#fi-tag-48"></use>
                    </svg>
                  </div>
                  <div className="block-features__content">
                    <div className="block-features__title">Hot Offers</div>
                    <div className="block-features__subtitle"> Discounts up to 90% </div>
                  </div>
                </div>
              </div>
            </div>
            </div>
          
          
          
          <FeaturedProducts/>
            
            
            
            
            <div className="block block-banner">
            <div className="container">
              <a href="#" className="block-banner__body">
                <div className="block-banner__image block-banner__image--desktop" style={{
                    backgroundImage: "url('images/banners/banner-1.jpg')",
                  }}></div>
                <div className="block-banner__image block-banner__image--mobile" style={{
                    backgroundImage:
                      "url('images/banners/banner-1-mobile.jpg')",
                  }}></div>
                <div className="block-banner__title"> Hundreds <br className="block-banner__mobile-br" /> Hand Tools </div>
                <div className="block-banner__text"> Hammers, Chisels, Universal Pliers, Nippers, Jigsaws, Saws </div>
                <div className="block-banner__button">
                  <span className="btn btn-sm btn-primary">Shop Now</span>
                </div>
              </a>
            </div>
          </div> {/*
          <!-- .block-banner / end -->
          <!-- .block-products --> */} <div className="block block-products block-products--layout--large-first" data-mobile-grid-columns="2">
            <div className="container">
              <div className="block-header">
                <h3 className="block-header__title">Bestsellers</h3>
                <div className="block-header__divider"></div>
              </div>
              <div className="block-products__body">
                <div className="block-products__featured">
                  <div className="block-products__featured-item">
                    <div className="product-card product-card--hidden-actions">
                      <button className="product-card__quickview" type="button">
                        <svg width="16px" height="16px">
                          <use xlinkHref="images/sprite.svg#quickview-16"></use>
                        </svg>
                        <span className="fake-svg-icon"></span>
                      </button>
                      <div className="product-card__badges-list">
                        <div className="product-card__badge product-card__badge--new"> New </div>
                      </div>
                      <div className="product-card__image product-image">
                        <a href="product.html" className="product-image__body">
                          <img className="product-image__img" src="images/products/product-1.jpg" alt="" />
                        </a>
                      </div>
                      <div className="product-card__info">
                        <div className="product-card__name">
                          <a href="product.html"> Electric Planer Brandix KL370090G 300 Watts </a>
                        </div>
                        <div className="product-card__rating">
                          <div className="product-card__rating-stars">
                            <div className="rating">
                              <div className="rating__body">
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-card__rating-legend"> 9 Reviews </div>
                        </div>
                        <ul className="product-card__features-list">
                          <li>Speed: 750 RPM</li>
                          <li>Power Source: Cordless-Electric</li>
                          <li>Battery Cell Type: Lithium</li>
                          <li>Voltage: 20 Volts</li>
                          <li>Battery Capacity: 2 Ah</li>
                        </ul>
                      </div>
                      <div className="product-card__actions">
                        <div className="product-card__availability"> Availability:{" "} <span className="text-success">In Stock</span>
                        </div>
                        <div className="product-card__prices">$749.00</div>
                        <div className="product-card__buttons">
                          <button className="btn btn-primary product-card__addtocart" type="button"> Add To Cart </button>
                          <button className="btn btn-secondary product-card__addtocart product-card__addtocart--list" type="button"> Add To Cart </button>
                          <button className="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__wishlist" type="button">
                            <svg width="16px" height="16px">
                              <use xlinkHref="images/sprite.svg#wishlist-16"></use>
                            </svg>
                            <span className="fake-svg-icon fake-svg-icon--wishlist-16"></span>
                          </button>
                          <button className="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__compare" type="button">
                            <svg width="16px" height="16px">
                              <use xlinkHref="images/sprite.svg#compare-16"></use>
                            </svg>
                            <span className="fake-svg-icon fake-svg-icon--compare-16"></span>
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                  <div className="block-products__list">
                    

                  <div className="block-products__list-item">
                    <div className="product-card product-card--hidden-actions">
                      <button className="product-card__quickview" type="button">
                        <svg width="16px" height="16px">
                          <use xlinkHref="images/sprite.svg#quickview-16"></use>
                        </svg>
                        <span className="fake-svg-icon"></span>
                      </button>
                      <div className="product-card__badges-list">
                        <div className="product-card__badge product-card__badge--hot"> Hot </div>
                      </div>
                      <div className="product-card__image product-image">
                        <a href="product.html" className="product-image__body">
                          <img className="product-image__img" src="images/products/product-2.jpg" alt="" />
                        </a>
                      </div>
                      <div className="product-card__info">
                        <div className="product-card__name">
                          <a href="product.html"> Undefined Tool IRadix DPS3000SY 2700 Watts </a>
                        </div>
                        <div className="product-card__rating">
                          <div className="product-card__rating-stars">
                            <div className="rating">
                              <div className="rating__body">
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-card__rating-legend"> 11 Reviews </div>
                        </div>
                        <ul className="product-card__features-list">
                          <li>Speed: 750 RPM</li>
                          <li>Power Source: Cordless-Electric</li>
                          <li>Battery Cell Type: Lithium</li>
                          <li>Voltage: 20 Volts</li>
                          <li>Battery Capacity: 2 Ah</li>
                        </ul>
                      </div>
                      <div className="product-card__actions">
                        <div className="product-card__availability"> Availability:{" "} <span className="text-success">In Stock</span>
                        </div>
                        <div className="product-card__prices">$1,019.00</div>
                        <div className="product-card__buttons">
                          <button className="btn btn-primary product-card__addtocart" type="button"> Add To Cart </button>
                          <button className="btn btn-secondary product-card__addtocart product-card__addtocart--list" type="button"> Add To Cart </button>
                          <button className="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__wishlist" type="button">
                            <svg width="16px" height="16px">
                              <use xlinkHref="images/sprite.svg#wishlist-16"></use>
                            </svg>
                            <span className="fake-svg-icon fake-svg-icon--wishlist-16"></span>
                          </button>
                          <button className="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__compare" type="button">
                            <svg width="16px" height="16px">
                              <use xlinkHref="images/sprite.svg#compare-16"></use>
                            </svg>
                            <span className="fake-svg-icon fake-svg-icon--compare-16"></span>
                          </button>
                        </div>
                      </div>
                    </div>
                    </div>
                    

                    
                  <div className="block-products__list-item">
                    <div className="product-card product-card--hidden-actions">
                      <button className="product-card__quickview" type="button">
                        <svg width="16px" height="16px">
                          <use xlinkHref="images/sprite.svg#quickview-16"></use>
                        </svg>
                        <span className="fake-svg-icon"></span>
                      </button>
                      <div className="product-card__image product-image">
                        <a href="product.html" className="product-image__body">
                          <img className="product-image__img" src="images/products/product-3.jpg" alt="" />
                        </a>
                      </div>
                      <div className="product-card__info">
                        <div className="product-card__name">
                          <a href="product.html"> Drill Screwdriver Brandix ALX7054 200 Watts </a>
                        </div>
                        <div className="product-card__rating">
                          <div className="product-card__rating-stars">
                            <div className="rating">
                              <div className="rating__body">
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-card__rating-legend"> 9 Reviews </div>
                        </div>
                        <ul className="product-card__features-list">
                          <li>Speed: 750 RPM</li>
                          <li>Power Source: Cordless-Electric</li>
                          <li>Battery Cell Type: Lithium</li>
                          <li>Voltage: 20 Volts</li>
                          <li>Battery Capacity: 2 Ah</li>
                        </ul>
                      </div>
                      <div className="product-card__actions">
                        <div className="product-card__availability"> Availability:{" "} <span className="text-success">In Stock</span>
                        </div>
                        <div className="product-card__prices">$850.00</div>
                        <div className="product-card__buttons">
                          <button className="btn btn-primary product-card__addtocart" type="button"> Add To Cart </button>
                          <button className="btn btn-secondary product-card__addtocart product-card__addtocart--list" type="button"> Add To Cart </button>
                          <button className="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__wishlist" type="button">
                            <svg width="16px" height="16px">
                              <use xlinkHref="images/sprite.svg#wishlist-16"></use>
                            </svg>
                            <span className="fake-svg-icon fake-svg-icon--wishlist-16"></span>
                          </button>
                          <button className="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__compare" type="button">
                            <svg width="16px" height="16px">
                              <use xlinkHref="images/sprite.svg#compare-16"></use>
                            </svg>
                            <span className="fake-svg-icon fake-svg-icon--compare-16"></span>
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="block-products__list-item">
                    <div className="product-card product-card--hidden-actions">
                      <button className="product-card__quickview" type="button">
                        <svg width="16px" height="16px">
                          <use xlinkHref="images/sprite.svg#quickview-16"></use>
                        </svg>
                        <span className="fake-svg-icon"></span>
                      </button>
                      <div className="product-card__badges-list">
                        <div className="product-card__badge product-card__badge--sale"> Sale </div>
                      </div>
                      <div className="product-card__image product-image">
                        <a href="product.html" className="product-image__body">
                          <img className="product-image__img" src="images/products/product-4.jpg" alt="" />
                        </a>
                      </div>
                      <div className="product-card__info">
                        <div className="product-card__name">
                          <a href="product.html"> Drill Series 3 Brandix KSR4590PQS 1500 Watts </a>
                        </div>
                        <div className="product-card__rating">
                          <div className="product-card__rating-stars">
                            <div className="rating">
                              <div className="rating__body">
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-card__rating-legend"> 7 Reviews </div>
                        </div>
                        <ul className="product-card__features-list">
                          <li>Speed: 750 RPM</li>
                          <li>Power Source: Cordless-Electric</li>
                          <li>Battery Cell Type: Lithium</li>
                          <li>Voltage: 20 Volts</li>
                          <li>Battery Capacity: 2 Ah</li>
                        </ul>
                      </div>
                      <div className="product-card__actions">
                        <div className="product-card__availability"> Availability:{" "} <span className="text-success">In Stock</span>
                        </div>
                        <div className="product-card__prices">
                          <span className="product-card__new-price"> $949.00 </span>
                          <span className="product-card__old-price"> $1189.00 </span>
                        </div>
                        <div className="product-card__buttons">
                          <button className="btn btn-primary product-card__addtocart" type="button"> Add To Cart </button>
                          <button className="btn btn-secondary product-card__addtocart product-card__addtocart--list" type="button"> Add To Cart </button>
                          <button className="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__wishlist" type="button">
                            <svg width="16px" height="16px">
                              <use xlinkHref="images/sprite.svg#wishlist-16"></use>
                            </svg>
                            <span className="fake-svg-icon fake-svg-icon--wishlist-16"></span>
                          </button>
                          <button className="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__compare" type="button">
                            <svg width="16px" height="16px">
                              <use xlinkHref="images/sprite.svg#compare-16"></use>
                            </svg>
                            <span className="fake-svg-icon fake-svg-icon--compare-16"></span>
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="block-products__list-item">
                    <div className="product-card product-card--hidden-actions">
                      <button className="product-card__quickview" type="button">
                        <svg width="16px" height="16px">
                          <use xlinkHref="images/sprite.svg#quickview-16"></use>
                        </svg>
                        <span className="fake-svg-icon"></span>
                      </button>
                      <div className="product-card__image product-image">
                        <a href="product.html" className="product-image__body">
                          <img className="product-image__img" src="images/products/product-5.jpg" alt="" />
                        </a>
                      </div>
                      <div className="product-card__info">
                        <div className="product-card__name">
                          <a href="product.html"> Brandix Router Power Tool 2017ERXPK </a>
                        </div>
                        <div className="product-card__rating">
                          <div className="product-card__rating-stars">
                            <div className="rating">
                              <div className="rating__body">
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-card__rating-legend"> 9 Reviews </div>
                        </div>
                        <ul className="product-card__features-list">
                          <li>Speed: 750 RPM</li>
                          <li>Power Source: Cordless-Electric</li>
                          <li>Battery Cell Type: Lithium</li>
                          <li>Voltage: 20 Volts</li>
                          <li>Battery Capacity: 2 Ah</li>
                        </ul>
                      </div>
                      <div className="product-card__actions">
                        <div className="product-card__availability"> Availability:{" "} <span className="text-success">In Stock</span>
                        </div>
                        <div className="product-card__prices">$1,700.00</div>
                        <div className="product-card__buttons">
                          <button className="btn btn-primary product-card__addtocart" type="button"> Add To Cart </button>
                          <button className="btn btn-secondary product-card__addtocart product-card__addtocart--list" type="button"> Add To Cart </button>
                          <button className="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__wishlist" type="button">
                            <svg width="16px" height="16px">
                              <use xlinkHref="images/sprite.svg#wishlist-16"></use>
                            </svg>
                            <span className="fake-svg-icon fake-svg-icon--wishlist-16"></span>
                          </button>
                          <button className="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__compare" type="button">
                            <svg width="16px" height="16px">
                              <use xlinkHref="images/sprite.svg#compare-16"></use>
                            </svg>
                            <span className="fake-svg-icon fake-svg-icon--compare-16"></span>
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="block-products__list-item">
                    <div className="product-card product-card--hidden-actions">
                      <button className="product-card__quickview" type="button">
                        <svg width="16px" height="16px">
                          <use xlinkHref="images/sprite.svg#quickview-16"></use>
                        </svg>
                        <span className="fake-svg-icon"></span>
                      </button>
                      <div className="product-card__image product-image">
                        <a href="product.html" className="product-image__body">
                          <img className="product-image__img" src="images/products/product-6.jpg" alt="" />
                        </a>
                      </div>
                      <div className="product-card__info">
                        <div className="product-card__name">
                          <a href="product.html"> Brandix Drilling Machine DM2019KW4 4kW </a>
                        </div>
                        <div className="product-card__rating">
                          <div className="product-card__rating-stars">
                            <div className="rating">
                              <div className="rating__body">
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-card__rating-legend"> 7 Reviews </div>
                        </div>
                        <ul className="product-card__features-list">
                          <li>Speed: 750 RPM</li>
                          <li>Power Source: Cordless-Electric</li>
                          <li>Battery Cell Type: Lithium</li>
                          <li>Voltage: 20 Volts</li>
                          <li>Battery Capacity: 2 Ah</li>
                        </ul>
                      </div>
                      <div className="product-card__actions">
                        <div className="product-card__availability"> Availability:{" "} <span className="text-success">In Stock</span>
                        </div>
                        <div className="product-card__prices">$3,199.00</div>
                        <div className="product-card__buttons">
                          <button className="btn btn-primary product-card__addtocart" type="button"> Add To Cart </button>
                          <button className="btn btn-secondary product-card__addtocart product-card__addtocart--list" type="button"> Add To Cart </button>
                          <button className="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__wishlist" type="button">
                            <svg width="16px" height="16px">
                              <use xlinkHref="images/sprite.svg#wishlist-16"></use>
                            </svg>
                            <span className="fake-svg-icon fake-svg-icon--wishlist-16"></span>
                          </button>
                          <button className="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__compare" type="button">
                            <svg width="16px" height="16px">
                              <use xlinkHref="images/sprite.svg#compare-16"></use>
                            </svg>
                            <span className="fake-svg-icon fake-svg-icon--compare-16"></span>
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="block-products__list-item">
                    <div className="product-card product-card--hidden-actions">
                      <button className="product-card__quickview" type="button">
                        <svg width="16px" height="16px">
                          <use xlinkHref="images/sprite.svg#quickview-16"></use>
                        </svg>
                        <span className="fake-svg-icon"></span>
                      </button>
                      <div className="product-card__image product-image">
                        <a href="product.html" className="product-image__body">
                          <img className="product-image__img" src="images/products/product-7.jpg" alt="" />
                        </a>
                      </div>
                      <div className="product-card__info">
                        <div className="product-card__name">
                          <a href="product.html">Brandix Pliers</a>
                        </div>
                        <div className="product-card__rating">
                          <div className="product-card__rating-stars">
                            <div className="rating">
                              <div className="rating__body">
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star rating__star--active" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge rating__star--active">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                                <svg className="rating__star" width="13px" height="12px">
                                  <g className="rating__fill">
                                    <use xlinkHref="images/sprite.svg#star-normal"></use>
                                  </g>
                                  <g className="rating__stroke">
                                    <use xlinkHref="images/sprite.svg#star-normal-stroke"></use>
                                  </g>
                                </svg>
                                <div className="rating__star rating__star--only-edge">
                                  <div className="rating__fill">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                  <div className="rating__stroke">
                                    <div className="fake-svg-icon"></div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-card__rating-legend"> 4 Reviews </div>
                        </div>
                        <ul className="product-card__features-list">
                          <li>Speed: 750 RPM</li>
                          <li>Power Source: Cordless-Electric</li>
                          <li>Battery Cell Type: Lithium</li>
                          <li>Voltage: 20 Volts</li>
                          <li>Battery Capacity: 2 Ah</li>
                        </ul>
                      </div>
                      <div className="product-card__actions">
                        <div className="product-card__availability"> Availability:{" "} <span className="text-success">In Stock</span>
                        </div>
                        <div className="product-card__prices">$24.00</div>
                        <div className="product-card__buttons">
                          <button className="btn btn-primary product-card__addtocart" type="button"> Add To Cart </button>
                          <button className="btn btn-secondary product-card__addtocart product-card__addtocart--list" type="button"> Add To Cart </button>
                          <button className="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__wishlist" type="button">
                            <svg width="16px" height="16px">
                              <use xlinkHref="images/sprite.svg#wishlist-16"></use>
                            </svg>
                            <span className="fake-svg-icon fake-svg-icon--wishlist-16"></span>
                          </button>
                          <button className="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__compare" type="button">
                            <svg width="16px" height="16px">
                              <use xlinkHref="images/sprite.svg#compare-16"></use>
                            </svg>
                            <span className="fake-svg-icon fake-svg-icon--compare-16"></span>
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div> {/* {/*
          <!-- .block-products / end -->
          <!-- .block-categories --> */}{" "} <div className="block block--highlighted block-categories block-categories--layout--classic">
            <div className="container">
              <div className="block-header">
                <h3 className="block-header__title">Popular Categories</h3>
                <div className="block-header__divider"></div>
              </div>
              <div className="block-categories__list">
                <div className="block-categories__item category-card category-card--layout--classic">
                  <div className="category-card__body">
                    <div className="category-card__image">
                      <a href="#">
                        <img src="images/categories/category-1.jpg" alt="" />
                      </a>
                    </div>
                    <div className="category-card__content">
                      <div className="category-card__name">
                        <a href="#">Power Tools</a>
                      </div>
                      <ul className="category-card__links">
                        <li>
                          <a href="#">Screwdrivers</a>
                        </li>
                        <li>
                          <a href="#">Milling Cutters</a>
                        </li>
                        <li>
                          <a href="#">Sanding Machines</a>
                        </li>
                        <li>
                          <a href="#">Wrenches</a>
                        </li>
                        <li>
                          <a href="#">Drills</a>
                        </li>
                      </ul>
                      <div className="category-card__all">
                        <a href="#">Show All</a>
                      </div>
                      <div className="category-card__products"> 572 Products </div>
                    </div>
                  </div>
                </div>
                <div className="block-categories__item category-card category-card--layout--classic">
                  <div className="category-card__body">
                    <div className="category-card__image">
                      <a href="#">
                        <img src="images/categories/category-2.jpg" alt="" />
                      </a>
                    </div>
                    <div className="category-card__content">
                      <div className="category-card__name">
                        <a href="#">Hand Tools</a>
                      </div>
                      <ul className="category-card__links">
                        <li>
                          <a href="#">Screwdrivers</a>
                        </li>
                        <li>
                          <a href="#">Hammers</a>
                        </li>
                        <li>
                          <a href="#">Spanners</a>
                        </li>
                        <li>
                          <a href="#">Handsaws</a>
                        </li>
                        <li>
                          <a href="#">Paint Tools</a>
                        </li>
                      </ul>
                      <div className="category-card__all">
                        <a href="#">Show All</a>
                      </div>
                      <div className="category-card__products"> 134 Products </div>
                    </div>
                  </div>
                </div>
                <div className="block-categories__item category-card category-card--layout--classic">
                  <div className="category-card__body">
                    <div className="category-card__image">
                      <a href="#">
                        <img src="images/categories/category-4.jpg" alt="" />
                      </a>
                    </div>
                    <div className="category-card__content">
                      <div className="category-card__name">
                        <a href="#">Machine Tools</a>
                      </div>
                      <ul className="category-card__links">
                        <li>
                          <a href="#">Lathes</a>
                        </li>
                        <li>
                          <a href="#">Milling Machines</a>
                        </li>
                        <li>
                          <a href="#">Grinding Machines</a>
                        </li>
                        <li>
                          <a href="#">CNC Machines</a>
                        </li>
                        <li>
                          <a href="#">Sharpening Machines</a>
                        </li>
                      </ul>
                      <div className="category-card__all">
                        <a href="#">Show All</a>
                      </div>
                      <div className="category-card__products"> 301 Products </div>
                    </div>
                  </div>
                </div>
                <div className="block-categories__item category-card category-card--layout--classic">
                  <div className="category-card__body">
                    <div className="category-card__image">
                      <a href="#">
                        <img src="images/categories/category-3.jpg" alt="" />
                      </a>
                    </div>
                    <div className="category-card__content">
                      <div className="category-card__name">
                        <a href="#">Power Machinery</a>
                      </div>
                      <ul className="category-card__links">
                        <li>
                          <a href="#">Generators</a>
                        </li>
                        <li>
                          <a href="#">Compressors</a>
                        </li>
                        <li>
                          <a href="#">Winches</a>
                        </li>
                        <li>
                          <a href="#">Plasma Cutting</a>
                        </li>
                        <li>
                          <a href="#">Electric Motors</a>
                        </li>
                      </ul>
                      <div className="category-card__all">
                        <a href="#">Show All</a>
                      </div>
                      <div className="category-card__products">79 Products</div>
                    </div>
                  </div>
                </div>
                <div className="block-categories__item category-card category-card--layout--classic">
                  <div className="category-card__body">
                    <div className="category-card__image">
                      <a href="#">
                        <img src="images/categories/category-5.jpg" alt="" />
                      </a>
                    </div>
                    <div className="category-card__content">
                      <div className="category-card__name">
                        <a href="#">Measurement</a>
                      </div>
                      <ul className="category-card__links">
                        <li>
                          <a href="#">Tape Measure</a>
                        </li>
                        <li>
                          <a href="#">Theodolites</a>
                        </li>
                        <li>
                          <a href="#">Thermal Imagers</a>
                        </li>
                        <li>
                          <a href="#">Calipers</a>
                        </li>
                        <li>
                          <a href="#">Levels</a>
                        </li>
                      </ul>
                      <div className="category-card__all">
                        <a href="#">Show All</a>
                      </div>
                      <div className="category-card__products"> 366 Products </div>
                    </div>
                  </div>
                </div>
                <div className="block-categories__item category-card category-card--layout--classic">
                  <div className="category-card__body">
                    <div className="category-card__image">
                      <a href="#">
                        <img src="images/categories/category-6.jpg" alt="" />
                      </a>
                    </div>
                    <div className="category-card__content">
                      <div className="category-card__name">
                        <a href="#">Clothes and PPE</a>
                      </div>
                      <ul className="category-card__links">
                        <li>
                          <a href="#">Winter Workwear</a>
                        </li>
                        <li>
                          <a href="#">Summer Workwear</a>
                        </li>
                        <li>
                          <a href="#">Helmets</a>
                        </li>
                        <li>
                          <a href="#">Belts and Bags</a>
                        </li>
                        <li>
                          <a href="#">Work Shoes</a>
                        </li>
                      </ul>
                      <div className="category-card__all">
                        <a href="#">Show All</a>
                      </div>
                      <div className="category-card__products">81 Products</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          
 

 
          
          
 
        </div>


        




      




      </div> {/*
      <!-- site / end -->
      <!-- quickview-modal --> */}
      
      
 

      
      


      <div className="pswp" tabIndex="-1" role="dialog" aria-hidden="true">
        <div className="pswp__bg"></div>
        <div className="pswp__scroll-wrap">
          <div className="pswp__container">
            <div className="pswp__item"></div>
            <div className="pswp__item"></div>
            <div className="pswp__item"></div>
          </div>
          <div className="pswp__ui pswp__ui--hidden">
            <div className="pswp__top-bar">
              <div className="pswp__counter"></div>
              <button className="pswp__button pswp__button--close" title="Close (Esc)"></button> {/*
              <!--<button className="pswp__button pswp__button&#45;&#45;share" title="Share"></button>--> */} <button className="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
              <button className="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
              <div className="pswp__preloader">
                <div className="pswp__preloader__icn">
                  <div className="pswp__preloader__cut">
                    <div className="pswp__preloader__donut"></div>
                  </div>
                </div>
              </div>
            </div>
            <div className="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
              <div className="pswp__share-tooltip"></div>
            </div>
            <button className="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></button>
            <button className="pswp__button pswp__button--arrow--right" title="Next (arrow right)"></button>
            <div className="pswp__caption">
              <div className="pswp__caption__center"></div>
            </div>
          </div>
        </div>
      </div>




    </div>
  );
}
